### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by aagravedu** [manan-shxrma/dsalgo#132]
I would like to add my recursive code to one of the famous problem Tower of Hanoi problems in C++.
please assign this issue to me 
and put the label as hacktoberfest2022 and good first issue. 
Thank You.

**Comment by aagravedu** [comment]
I would like to work on this please assign this issue to me.

**Comment by manan-shxrma** [comment]
sure, you may go for it

**Comment by aagravedu** [comment]
Hey, I have created a PR under hacktoberfest 2022.  Please review my PR if everything seems fine to u. then merge my 
pr and put the label as hacktoberfest accepted.
In case of any changes do let me know.
Thank You.
