### ISSUE TITLE
Steiner Tree implementation in c

### ISSUE THREAD

**Issue by abhishektyagi2912** [manan-shxrma/dsalgo#209]
add a Steiner Tree CPP code in the tree folder that is also helping many of the students because this approach is not known to many of us primarily those who are in college and preparing for competitive coding.

**Comment by abhishektyagi2912** [comment]
plz assign me this issue under hack October fest

**Comment by manan-shxrma** [comment]
give a brief description of this issue

**Comment by abhishektyagi2912** [comment]
done
