### ISSUE TITLE
Adding a .gitignore to not commit executable files

### ISSUE THREAD

**Issue by meetagrawal09** [manan-shxrma/dsalgo#43]
In the Graph directory, I see every code has it's **_.exe_** file committed to the repository (which is not a good practice)

**Comment by meetagrawal09** [comment]
@manan-shxrma, if you can please confirm the issue

**Comment by manan-shxrma** [comment]
great @meetagrawal09 you can solve this issue

**Comment by meetagrawal09** [comment]
Made a PR for this #50
