### ISSUE TITLE
Doubt regarding Contribution

### ISSUE THREAD

**Issue by dhairyaostwal** [manan-shxrma/dsalgo#72]
Hey @manan-shxrma greetings!

I want to add in frequently asked Question Solutions. So am I allowed to create PR and so forth would you be assigning `hacktober-accepted` tag followed by merge?

**Comment by manan-shxrma** [comment]
> Hey @manan-shxrma greetings!
> 
> I want to add in frequently asked Question Solutions. So am I allowed to create PR and so forth would you be assigning `hacktober-accepted` tag followed by merge?

Yeah, just it should be bug-free and should not violate copyright infringement. Moreover it should be a unique problem that has not already been added to codebase
