### ISSUE TITLE
Add next permutation 

### ISSUE THREAD

**Issue by zugzwang03** [manan-shxrma/dsalgo#83]
I am creating an issue because the next permutation function in cpp can be easily made using built-in functions, but in c, it is not so easy. So I want to add this new algorithm here for this question :
https://leetcode.com/problems/next-permutation/
I want to make this contribution under Hacktoberfest'22.
And I will include this file in sortings directory.

**Comment by manan-shxrma** [comment]
> I am creating an issue because the next permutation function in cpp can be easily made using built-in functions, but in c, it is not so easy. So I want to add this new algorithm here for this question : https://leetcode.com/problems/next-permutation/ I want to make this contribution under Hacktoberfest'22. And I will include this file in sortings directory.

this repository encourages use of c++ language, so please make sure to code your contributions in the same.
