### ISSUE TITLE
Add "check for balanced parenthesis"

### ISSUE THREAD

**Issue by zugzwang03** [manan-shxrma/dsalgo#88]
I want to add the new program of "check for balanced parenthesis" in the stack directory of your project.
I want to make this contribution under hacktoberfest'22.
Question link : https://leetcode.com/problems/valid-parentheses/

**Comment by manan-shxrma** [comment]
> I want to add the new program of "check for balanced parenthesis" in the stack directory of your project. I want to make this contribution under hacktoberfest'22. Question link : https://leetcode.com/problems/valid-parentheses/

go for it
